name: release

on:
    push:
        branches:
            - master:
                tags: [ 'v*' ]
      
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Test the release script
              run: echo "I ran"